### ISSUE TITLE
To-do list input block can be duplicated

### ISSUE THREAD

**Issue by Tetramad** [Kwon770/focus-timer#2]
# Detail

In to-do list setting, input block can be duplicated. And sometime I can't input text in that. Refreshing browser can be temporary fixing.

# How to re-invoke bug

1. Open to-do list setting
2. Click pencil icon
3. Close to-do list setting somehow. e.g. click left chevron in setting window.
4. Re-open to-do list setting
5. Click pencil icon again.
6. Duplicate

**Comment by Kwon770** [comment]
I fix it.
**Thanks for contribution**
